### ISSUE TITLE
Paste not emiting complete

### ISSUE THREAD

**Issue by ivalkenburg** [wobsoriano/vue-input-otp#10]
If maxlength = 6 and pasting a numeric string of 6 numbers it does not emit complete event.

Seems to be only emiting complete with manual input.

Eitherway, really like this implementation of otp input.

**Comment by wobsoriano** [comment]
Thank you for reporting that! I'll defo check it asap :)

**Comment by ivalkenburg** [comment]
Seems to not emit complete when pasting into an empty or fully filled input. But if there is partial input it does emit complete.

I'm using firefox.
