### ISSUE TITLE
Nuxt 3 Cannot destructure property 'slots' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by productdevbook** [wobsoriano/vue-input-otp#3]
![CleanShot 2024-02-23 at 08 32 28](https://github.com/wobsoriano/vue-input-otp/assets/38668796/beeffa51-9c12-4354-b38e-fc3d38481eaa)

**Comment by walmartwarlord** [comment]
Thanks for testing this out! I'll take a look

**Comment by wobsoriano** [comment]
Tried it on a fresh Nuxt project and got it working 🤔 Will investigate

**Comment by wobsoriano** [comment]
Hey, the website is now using Nuxt :) https://github.com/wobsoriano/vue-input-otp/tree/main/website

**Comment by productdevbook** [comment]
Thank you
