### ISSUE TITLE
Ability for focus previously filled segments

### ISSUE THREAD

**Issue by sadeghbarati** [wobsoriano/vue-input-otp#9]
https://rci.netlify.app/

https://github.com/wobsoriano/vue-input-otp/assets/17789047/7ac32a46-806b-470a-999d-1a91ed51ad5f

**Comment by wobsoriano** [comment]
Hey man! I try to make this project remain aligned with [input-otp](https://github.com/guilhermerodz/input-otp) which does not have this feature as well. I'll try to ask the original author if he plans on doing it, and if it breaks something (accessibility wise), then I'll let you know :)

**Comment by walmartwarlord** [comment]
https://github.com/guilhermerodz/input-otp/issues/32
